sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: TvzvMPi1fKY68lxq62TOahEeOV50EpW3PpmqEDC6LdPitGEaPnj0M/nVrRoemU1mwbLnGCA8i0zXO0PsNa4Xi2oql8vZcgxJB2W+pbjQQveOaYBstFPn4JngFLtlvcONlzs8DUtdsx3GhabrDkyOc9DcMl3DT5O4lj/pZGpG9Cz1lYogBafyotEatAoO4+2n8/a2D6TQxT1o4R70DWMrCHE5/jTywfpGyYMJKlW2we7CgszqmfCLtZCE8G9I6XEZHe03bGisv1zKbvxJLzCjXBzxul5KY5F1Fhxs0xIuwx30mCgdOqTrZV+Zg8F4RoCcglk4ILLg0w9OmVYkdpJXtjcXr9+55lsvJ0tTCgZC9lOO9HHJ3Ql3CzNYvi/H5W66vC9CKmJ7/NZzZPXaAFOjnihnEQTr3EXaaT3kjiQ6WSEk9b7gILQ6Pq5CZLGSvHW5ZgbMZMpx6BOHxr115z5DdBqM1RgznOvFc5Ui02H919EoUBsUuU/pL6zCFlGHlIiwbtzXtBMdidnkWmxBvfGr5KDvIOOTmWLqocYQiIg7sV+m/7bJG0NegsL+E8YxymwZ1I+MkkE95BEpKeDPyu5f0w/zzfHVEKJ/NU3Tf9Bv00EY+OnGBE/lCO2iJUn7TLrNRbu0os5QcVl9nW0m2Gnqw+ARTu7XbxtqOSZPZSiN7fw=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Memoirs-of-Napoleon-Bonaparte-Volume-10_3560
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy